### ISSUE TITLE
Add support for web

### ISSUE THREAD

**Issue by necolas** [hectahertz/react-native-typography#2]
I think this could be really useful for people building web apps with React Native (e.g., using react-native-web). Web apps built with RNW will default the OS system font, but may want to switch between human/material depending on the platform the browser runs on. Do you any questions or thoughts about how to support web?

**Comment by kgoggin** [comment]
I'm definitely interested in seeing this lib work with RNW and have been playing around with it a little. I'm coming at it with the expectation that I'd be using the "Object" exports provided by this lib so that I can call `Stylesheet.create` in my own code and have RNW's babel transform pick it up and work its magic.

That said, the main (only?) issue I'm experiencing is the usage of `Platform.select` inside `systemWeight.js`. As there's no `default` or `web` option, each of the weights ends up being `undefined` when used with RNW. I've worked around this by adding a check for an `undefined` value for a specific weight at the point of use and providing my own "fallback" for web: 

```javascript
import { systemWeights } from 'react-native-typography';

// grabbed this font stack from the RNW code...
const webThin = {
  fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Ubuntu, "Helvetica Neue", sans-serif',
  fontWeight: '300',
  backgroundColor: 'transparent'
};

const thin = systemWeights.thin || webThin;

// use in StyleSheet.create(), etc.
```

To solve this at the library level, you could add a `web` option to the system weights, possibly using RNW's font stack plus some reasonable weights?. I think the main value to that would be not having it just "fail" basically silently with RNW, but I wonder how many people wouldn't be trying to overwrite these defaults anyway?

It looks like the other places you're using `Platform` is to provide spacing for San Francisco. I suppose ideally that'd get applied when `-apple-system` _is_ San Francisco, but I'm not sure of a great way to do that?

**Comment by necolas** [comment]
I'm not sure what problem you're having. RNW doesn't depend on Babel to transform styles and you should be able to use the `System` font family name as RNW will transform that for you. I'll take a closer look this week to understand more. Thanks

**Comment by kgoggin** [comment]
Sorry if I wasn't clear. There's no issue with RNW. Rather, this library is using `Platform.select()` without a `web` or `default` option to generate the system weights, so when you use it with RNW the system weights all come back `undefined`.

I didn't know RNW will transform the `System` font name - that's cool!

**Comment by necolas** [comment]
Ah, i understand now. Thank you. What if `android` were changed to `default` system?

**Comment by hectahertz** [comment]
Thanks for your comments!

What do you think of [this quick implementation](https://github.com/hectahertz/react-native-typography/commit/a2b6a73b1bdb3793e91513d1f609c4ba28f56779)?

For the San Francisco system font, [Chrome](https://chromium.googlesource.com/chromium/src/+/487f920d800195ee2d5de599ac0f647720627dc4) and [Safari](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_9_0.html) already handle the kerning and the SF Text/Display change, so there's no need for special treatment.

**Comment by jsp3536** [comment]
I am trying to get this library working for react-native-windows and ran into a similar problem where systemWeights was undefined.  I got the library working by making a systemDenseWeights.windows.js, systemTallWeights.windows.js,  and systemWeights.windows.js files.  Is this the best ways to do this or is there another way the can be done to default the imports when Platform.OS is unknown?
